import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "./components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-stone-950 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-sm:hidden flex justify-center ">
          <NavBar />
        </div>
        <div className="hidden max-sm:flex ">
          <NavBar />
        </div>
        <div className="z-0 ">
        {children}
        </div>
       
      </body>
    </html>
  );
}
